config:
  azure-native:location: westeurope
  ptx:prefix: godotfest
  ptx:vmSize: Standard_B2s
  ptx:pretixImageTag: stable
  ptx:pretalxImageTag: latest
  ptx:mailFrom: DoNotReply@godotfest.com
  # Required — set before running `pulumi up`:

  ptx:domain: godotfest.com
  ptx:sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCXKsPDUWpQHp8W/Up6FdAnlnCk5atme5Nzdg5Tms3vpDjV01xzD4udpibWVm3JGfNqw8B4xzDIC+hSZAcgPVlehyoX/kyNz4TSQtHLEaVsuHeRxzcnB5NEW1fVqmYxI+XayduLG64HkvdlVz/8GmEtuoWB7pmc8QdKaSGBchkw7wA2h1eIgL1l7huy5xisOvTALIZqKUmqu3uYVSRcbfqT6PASwzlYVbhOoJFW3jj50lkYOv3euhAJOjpx9PzntJJBnvHKTz1ldYiALnEJGvNChAcqclNcBh+mI7Sj9kfyW9Ofh4sQN7aydMwz32uRfYxqUJ6lXz7tZxp61ilwsG5C9aFPsXkeq7bw9/cRMg3Sv2qAvGkNXCXS4BF8vkMRF0CTVcuY0bHX3B8PsDfmgKe155ATTNT3qXITY+wnVfl0tz45ofH7JAJlA+UHEkhh8H31zSYyWEKbsnI4tBKfKpIr4nsR6sG5dObC4UEGb/gstfbj6kCCRmRDVax259GltRBtGUbuSNhbxqeGpWcTHLgHrvOfBRo09yFPEc/utCvCl+XpfPehUwyzEbigy8CgNqOzRCgjOaoDQpoQyF/+3cRhnWiW1fik64sS+l3f0jEFRTaLZ+a0oYr3SiebEJpgsyPYwdy5bQ4AmpUjgw5z4EbcWGIUXIQzySft7/E/8hFnyw==
  ptx:smtpHost: smtp.azurecomm.net
  ptx:smtpPort: "587"
  ptx:smtpUser: godotfest-web-communication-services-eu.293a0707-6a9d-4f84-9199-c38446763d56.b9b56bc4-19cb-4686-b32d-ec36a6b2baad
  ptx:smtpPassword:
    secure: AAABAOZkxeOJVSFA448OXkqbjW6P84XsrFoZUzM3n0vi8zkcfzc/FfothksEF+5P4mHR1ktLLrPNe3jmdpWrUds5xzq6sZNQ
  ptx:cloudflareApiToken:
    secure: AAABAEh0QbBASGa5DoPEMMigyPI5QfIL9Gvh9oQopsgn3MV0C9J7A6cY+eRdNyAfwW1ly85Yo67fcE6QF+fnKvu29wHnvfxLJcFO9B2RmMwb0bG7ag==
  ptx:cloudflareZoneId: 3191caf42094e04b63439d70094f4b26
  ptx:cloudflareDnsChallenge: "true"
  ptx:adminEmail: johannes@godotfest.com
  ptx:useAzureMail: "true"
  ptx:acsUseCustomDomain: "false"

# ptx:domain: yourdomain.com

# ptx:sshPublicKey: ssh-rsa AAAA...

# Optional — Cloudflare DNS automation:

# ptx:cloudflareApiToken: <secret>

# ptx:cloudflareZoneId: <zone-id>

# ptx:cloudflareDnsChallenge: "false"

# Optional — SMTP:

# ptx:smtpHost: smtp.example.com

# ptx:smtpPort: "587"

# ptx:smtpUser: user

# ptx:smtpPassword: <secret>
